version: "3"
services:
  redis:
    image: redis:alpine
    networks: 
      - webnet
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gignal
  web:
    image: gignal-server
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on: 
      - db
      - redis
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./mysite.template
  #   ports:
  #     - "4000:40"
  #   networks: 
  #     - webnet
  #   depends_on: 
  #     - web
networks:
  webnet: